name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

exclude-labels:
  - github-bot ğŸ¤–

categories:
  - title: ğŸ› ï¸ Breaking Changes
    labels:
      - breaking-change ğŸ› ï¸

  - title: ğŸš€ Features
    labels:
      - feature ğŸš€
      - enhancement ğŸ€

  - title: ğŸ’ New Functions
    labels:
      - new-function ğŸ’

  - title: ğŸ Bug Fixes
    labels:
      - bug ğŸ

  - title: ğŸ’» Application
    labels:
      - app ğŸ’»

  - title: ğŸ§± Infrastructure
    labels:
      - infra ğŸ§±

  - title: ğŸ›¡ï¸ Tests
    labels:
      - tests ğŸ›¡ï¸

  - title: âš™ï¸ Configuration and Maintenance
    labels:
      - config âš™ï¸

  - title: ğŸ–ï¸ Documentation
    labels:
      - doc ğŸ–ï¸
      
  - title: Other Changes
    labels:
      - "*"

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - breaking-change ğŸ› ï¸
  minor:
    labels:
      - feature ğŸš€
      - enhancement ğŸ€
  patch:
    labels:
      - app ğŸ’»
      - infra ğŸ§±
      - tests ğŸ›¡ï¸
      - bug ğŸ
      - doc ğŸ–ï¸
      - observability ğŸ‘ï¸â€ğŸ—¨ï¸
      - config âš™ï¸
      - new-function ğŸ’
  
  default: patch

template: |
  ## Changes

  $CHANGES
