name: "âš™ï¸ CI feature branch"

on:
  push:
    branches:
      - feature**

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  ci-python:
    name: ci-python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Installation
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Dependencies Installation
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/dev.txt
      
      - name: AnÃ¡lise de Linter - flake8
        run:
          flake8 . --ignore E501
  
  #ci-glue-docker-pytest:
  #  name: ci-glue-docker-pytest
  #  runs-on: ubuntu-latest
  #  needs:
  #    - ci-python

  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v3

  #    - name: Unit Test on Glue 3.0 Docker Image
  #      uses: addnab/docker-run-action@v3
  #      with:
  #        image: amazon/aws-glue-libs:glue_libs_3.0.0_image_01
  #        options: |
  #          -u root
  #          -v ${{ github.workspace }}:/home/glue_user/workspace/github-project
  #          -e DISABLE_SSL=true
  #          -e AWS_ACCESS_KEY_ID="a-fake-access-key-id"
  #          -e AWS_SECRET_ACCESS_KEY="a-secret-access-key"
  #          -e AWS_REGION="us-east-1"
  #          --rm
  #          -p 4040:4040 -p 18080:18080
  #          --name github-project
  #        run: |
  #          cd github-project
  #          python3 -m pip install --user --upgrade pip -r requirements/dev.txt
  #          python3 -m pytest -vv --color=yes --cov=./ --cov-report=xml

  #    - name: Test Coverage with Codecov
  #      uses: codecov/codecov-action@v3
  #      with:
  #        token: ${{ secrets.CODECOV_TOKEN }}

  open-pr-to-main:
    name: open-pr-to-main
    runs-on: ubuntu-latest
    needs:
      #- ci-glue-docker-pytest
      - ci-python

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PR to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref }}
          destination_branch: "main"
          pr_title: "pr(main): ${{ github.ref }} -> main"
          pr_template: ".github/pull_request_template.md"
          pr_assignee: "ThiagoPanini"
          pr_label: "github-bot ðŸ¤–"
          github_token: ${{ secrets.GITHUB_TOKEN }}
