name: "[1]âš™ï¸ CI terraglue - feature branch"

on:
  push:
    branches:
      - feature**

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  ci-python:
    name: ci-python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: InstalaÃ§Ã£o do Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: InstalaÃ§Ã£o das DependÃªncias
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./app/requirements-ci.txt
      
      - name: AnÃ¡lise de Linter - flake8
        run:
          flake8 . --ignore E501

      - name: AnÃ¡lise de Docstrings - pydocstyle
        run:
          pydocstyle --match-dir ./app/src/*.py

  ci-terraform:
    name: ci-terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ConfiguraÃ§Ã£o de Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: OIDCSession
          aws-region: sa-east-1

      - name: ConfiguraÃ§Ã£o e Setup do Terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform init
        run: |
          cd infra/
          terraform init

      - name: terraform plan
        run: |
          cd infra/
          terraform plan
        continue-on-error: false

  open-pr-to-dev:
    name: open-pr-to-dev
    runs-on: ubuntu-latest
    needs:
      - ci-python
      - ci-terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cria PR para dev
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref }}
          destination_branch: "develop"
          pr_title: "[PREENCHER] ${{ github.ref }} -> develop"
          pr_template: ".github/pull_request_template.md"
          pr_assignee: "ThiagoPanini"
          pr_label: github-bot ðŸ¤–
          github_token: ${{ secrets.GITHUB_TOKEN }}
